export enum Districts {
  // 서울특별시
  JongnoGu = 11110,
  JungGuSeoul = 11140,
  YongsanGu = 11170,
  SeongdongGu = 11200,
  GwangjinGu = 11215,
  DongdaemunGu = 11230,
  JungnangGu = 11260,
  SeongbukGu = 11290,
  GangbukGu = 11305,
  DobongGu = 11320,
  NowonGu = 11350,
  EunpyeongGu = 11380,
  SeodaemunGu = 11410,
  MapoGu = 11440,
  YangcheonGu = 11470,
  GangseoGuSeoul = 11500,
  GuroGu = 11530,
  GeumcheonGu = 11545,
  YeongdeungpoGu = 11560,
  DongjakGu = 11590,
  GwanakGu = 11620,
  SeochoGu = 11650,
  GangnamGu = 11680,
  SongpaGu = 11710,
  GangdongGu = 11740,
  // 부산광역시
  JungGuBusan = 26110,
  SeoGuBusan = 26140,
  DongGuBusan = 26170,
  YeongdoGu = 26200,
  BusanjinGu = 26230,
  DongnaeGu = 26260,
  NamGuBusan = 26290,
  BukGuBusan = 26320,
  HaeundaeGu = 26350,
  SahaGu = 26380,
  GeumjeongGu = 26410,
  GangseoGuBusan = 26440,
  YeonjeGu = 26470,
  SuyeongGu = 26500,
  SasangGu = 26530,
  GijangGun = 26710,
  // 대구광역시
  JungGuDaegu = 27110,
  DongGuDaegu = 27140,
  SeoGuDaegu = 27170,
  NamGuDaegu = 27200,
  BukGuDaegu = 27230,
  SuseongGu = 27260,
  DalseoGu = 27290,
  DalseongGun = 27710,
  // 인천광역시
  JungGuIncheon = 28110,
  DongGuIncheon = 28140,
  MichuholGu = 28177,
  YeonsuGu = 28185,
  NamdongGu = 28200,
  BupyeongGu = 28237,
  GyeyangGu = 28245,
  SeoGuIncheon = 28260,
  GanghwaGun = 28710,
  OngjinGun = 28720,
  // 광주광역시
  DongGuGwangju = 29110,
  SeoGuGwangju = 29140,
  NamGuGwangju = 29155,
  BukGuGwangju = 29170,
  GwangsanGu = 29200,
  // 대전광역시
  DongGuDaejeon = 30110,
  JungGuDaejeon = 30140,
  SeoGuDaejeon = 30170,
  YuseongGu = 30200,
  DaedeokGu = 30230,
  // 울산광역시
  JungGuUlsan = 31110,
  NamGuUlsan = 31140,
  DongGuUlsan = 31170,
  BukGuUlsan = 31200,
  UljuGun = 31710,
  // 세종특별자치시
  Sejong = 36110,
  // 경기도
  SuwonSi = 41110,
  SeongnamSi = 41130,
  UijeongbuSi = 41150,
  AnyangSi = 41170,
  BucheonSi = 41190,
  GwangmyeongSi = 41210,
  PyeongtaekSi = 41220,
  DongducheonSi = 41250,
  AnsanSi = 41270,
  GoyangSi = 41280,
  GwacheonSi = 41290,
  GuriSi = 41310,
  NamyangjuSi = 41360,
  OsanSi = 41370,
  SiheungSi = 41390,
  GunpoSi = 41410,
  UiwangSi = 41430,
  HanamSi = 41450,
  YonginSi = 41460,
  PajuSi = 41480,
  IcheonSi = 41500,
  AnseongSi = 41550,
  GimpoSi = 41570,
  HwaseongSi = 41590,
  GwangjuSi = 41610,
  YangjuSi = 41630,
  PocheonSi = 41650,
  YeojooSi = 41670,
  YeoncheonGun = 41800,
  GapyeongGun = 41820,
  YangpyeongGun = 41830,
  // 강원도
  ChuncheonSi = 51110,
  WonjuSi = 51130,
  GangneungSi = 51150,
  DonghaeSi = 51170,
  TaebaekSi = 51190,
  SokchoSi = 51210,
  SamcheokSi = 51230,
  HongcheonGun = 51720,
  HoengseongGun = 51730,
  YeongwolGun = 51750,
  PyeongchangGun = 51760,
  JeongseonGun = 51770,
  CheorwonGun = 51780,
  HwacheonGun = 51790,
  YangguGun = 51800,
  InjeGun = 51810,
  GoseongGunGangwon = 51820,
  YangyangGun = 51830,
  // 충청북도
  CheongjuSi = 43110,
  ChungjuSi = 43130,
  JecheonSi = 43150,
  BoeunGun = 43720,
  OkcheonGun = 43730,
  YeongdongGun = 43740,
  JeungpyeongGun = 43745,
  JincheonGun = 43750,
  GoesanGun = 43760,
  EumseongGun = 43770,
  DanyangGun = 43800,
  // 충청남도
  CheonanSi = 44130,
  GongjuSi = 44150,
  BoryeongSi = 44180,
  AsanSi = 44200,
  SeosanSi = 44210,
  NonsanSi = 44230,
  GyeryongSi = 44250,
  DangjinSi = 44270,
  GeumsanGun = 44710,
  BuyeoGun = 44760,
  SeocheonGun = 44770,
  CheongyangGun = 44790,
  HongseongGun = 44800,
  YesanGun = 44810,
  TaeanGun = 44825,
  // 전라북도
  JeonjuSi = 45110,
  GunsanSi = 45130,
  IksanSi = 45140,
  JeongeupSi = 45180,
  NamwonSi = 45190,
  GimjeSi = 45210,
  WanjuGun = 45710,
  JinanGun = 45720,
  MujuGun = 45730,
  JangsuGun = 45740,
  ImsilGun = 45750,
  SunchangGun = 45770,
  GochangGun = 45790,
  BuanGun = 45800,
  // 전라남도
  MokpoSi = 46110,
  YeosuSi = 46130,
  SuncheonSi = 46150,
  NajuSi = 46170,
  GwangyangSi = 46230,
  DamyangGun = 46710,
  GokseongGun = 46720,
  GuryeGun = 46730,
  GoheungGun = 46770,
  BoseongGun = 46780,
  HwasunGun = 46790,
  JangheungGun = 46800,
  GangjinGun = 46810,
  HaenamGun = 46820,
  YeongamGun = 46830,
  MuanGun = 46840,
  HampyeongGun = 46860,
  YeonggwangGun = 46870,
  JangseongGun = 46880,
  WandoGun = 46890,
  JindoGun = 46900,
  SinanGun = 46910,
  // 경상북도
  PohangSi = 47110,
  GyeongjuSi = 47130,
  GimcheonSi = 47150,
  AndongSi = 47170,
  GumiSi = 47190,
  YeongjuSi = 47210,
  YeongcheonSi = 47230,
  SangjuSi = 47250,
  MungyeongSi = 47280,
  GyeongsanSi = 47290,
  GunwiGun = 47720,
  UiseongGun = 47730,
  CheongsongGun = 47750,
  YeongyangGun = 47760,
  YeongdeokGun = 47770,
  CheongdoGun = 47820,
  GoryeongGun = 47830,
  SeongjuGun = 47840,
  ChilgokGun = 47850,
  YecheonGun = 47900,
  BonghwaGun = 47920,
  UljinGun = 47930,
  UlleungGun = 47940,
  // 경상남도
  ChangwonSi = 48120,
  JinjuSi = 48170,
  TongyeongSi = 48220,
  SacheonSi = 48240,
  GimhaeSi = 48250,
  MiryangSi = 48270,
  GeojeSi = 48310,
  YangsanSi = 48330,
  UiryeongGun = 48720,
  HamanGun = 48730,
  ChangnyeongGun = 48740,
  GoseongGunGyeongsangnam = 48820,
  NamhaeGun = 48840,
  HadongGun = 48850,
  SancheongGun = 48860,
  HamyangGun = 48870,
  GeochangGun = 48880,
  HapcheonGun = 48890,
  // 제주특별자치도
  JejuSi = 50110,
  Seogwipo = 50130,
}
const districtDescriptions: { [key in Districts]: string } = {
  // 서울특별시
  [Districts.JongnoGu]: "종로구",
  [Districts.JungGuSeoul]: "중구",
  [Districts.YongsanGu]: "용산구",
  [Districts.SeongdongGu]: "성동구",
  [Districts.GwangjinGu]: "광진구",
  [Districts.DongdaemunGu]: "동대문구",
  [Districts.JungnangGu]: "중랑구",
  [Districts.SeongbukGu]: "성북구",
  [Districts.GangbukGu]: "강북구",
  [Districts.DobongGu]: "도봉구",
  [Districts.NowonGu]: "노원구",
  [Districts.EunpyeongGu]: "은평구",
  [Districts.SeodaemunGu]: "서대문구",
  [Districts.MapoGu]: "마포구",
  [Districts.YangcheonGu]: "양천구",
  [Districts.GangseoGuSeoul]: "강서구",
  [Districts.GuroGu]: "구로구",
  [Districts.GeumcheonGu]: "금천구",
  [Districts.YeongdeungpoGu]: "영등포구",
  [Districts.DongjakGu]: "동작구",
  [Districts.GwanakGu]: "관악구",
  [Districts.SeochoGu]: "서초구",
  [Districts.GangnamGu]: "강남구",
  [Districts.SongpaGu]: "송파구",
  [Districts.GangdongGu]: "강동구",

  // 부산광역시
  [Districts.JungGuBusan]: "중구",
  [Districts.SeoGuBusan]: "서구",
  [Districts.DongGuBusan]: "동구",
  [Districts.YeongdoGu]: "영도구",
  [Districts.BusanjinGu]: "부산진구",
  [Districts.DongnaeGu]: "동래구",
  [Districts.NamGuBusan]: "남구",
  [Districts.BukGuBusan]: "북구",
  [Districts.HaeundaeGu]: "해운대구",
  [Districts.SahaGu]: "사하구",
  [Districts.GeumjeongGu]: "금정구",
  [Districts.GangseoGuBusan]: "강서구",
  [Districts.YeonjeGu]: "연제구",
  [Districts.SuyeongGu]: "수영구",
  [Districts.SasangGu]: "사상구",
  [Districts.GijangGun]: "기장군",

  // 대구광역시
  [Districts.JungGuDaegu]: "중구",
  [Districts.DongGuDaegu]: "동구",
  [Districts.SeoGuDaegu]: "서구",
  [Districts.NamGuDaegu]: "남구",
  [Districts.BukGuDaegu]: "북구",
  [Districts.SuseongGu]: "수성구",
  [Districts.DalseoGu]: "달서구",
  [Districts.DalseongGun]: "달성군",

  // 인천광역시
  [Districts.JungGuIncheon]: "중구",
  [Districts.DongGuIncheon]: "동구",
  [Districts.MichuholGu]: "미추홀구",
  [Districts.YeonsuGu]: "연수구",
  [Districts.NamdongGu]: "남동구",
  [Districts.BupyeongGu]: "부평구",
  [Districts.GyeyangGu]: "계양구",
  [Districts.SeoGuIncheon]: "서구",
  [Districts.GanghwaGun]: "강화군",
  [Districts.OngjinGun]: "옹진군",

  // 광주광역시
  [Districts.DongGuGwangju]: "동구",
  [Districts.SeoGuGwangju]: "서구",
  [Districts.NamGuGwangju]: "남구",
  [Districts.BukGuGwangju]: "북구",
  [Districts.GwangsanGu]: "광산구",

  // 대전광역시
  [Districts.DongGuDaejeon]: "동구",
  [Districts.JungGuDaejeon]: "중구",
  [Districts.SeoGuDaejeon]: "서구",
  [Districts.YuseongGu]: "유성구",
  [Districts.DaedeokGu]: "대덕구",

  // 울산광역시
  [Districts.JungGuUlsan]: "중구",
  [Districts.NamGuUlsan]: "남구",
  [Districts.DongGuUlsan]: "동구",
  [Districts.BukGuUlsan]: "북구",
  [Districts.UljuGun]: "울주군",

  // 세종특별자치시
  [Districts.Sejong]: "세종특별자치시",

  // 경기도
  [Districts.SuwonSi]: "수원시",
  [Districts.GwangmyeongSi]: "광명시",
  [Districts.PyeongtaekSi]: "평택시",
  [Districts.DongducheonSi]: "동두천시",
  [Districts.AnsanSi]: "안산시",
  [Districts.GwacheonSi]: "과천시",
  [Districts.GuriSi]: "구리시",
  [Districts.NamyangjuSi]: "남양주시",
  [Districts.OsanSi]: "오산시",
  [Districts.SiheungSi]: "시흥시",
  [Districts.GunpoSi]: "군포시",
  [Districts.HanamSi]: "하남시",
  [Districts.UijeongbuSi]: "의정부시",
  [Districts.UiwangSi]: "의왕시",
  [Districts.PajuSi]: "파주시",
  [Districts.IcheonSi]: "이천시",
  [Districts.AnseongSi]: "안성시",
  [Districts.GimpoSi]: "김포시",
  [Districts.HwaseongSi]: "화성시",
  [Districts.GwangjuSi]: "광주시",
  [Districts.YangjuSi]: "양주시",
  [Districts.PocheonSi]: "포천시",
  [Districts.YeojooSi]: "여주시",
  [Districts.YeoncheonGun]: "연천군",
  [Districts.GapyeongGun]: "가평군",
  [Districts.YangpyeongGun]: "양평군",
  [Districts.SeongnamSi]: "성남시",
  [Districts.AnyangSi]: "안양시",
  [Districts.BucheonSi]: "부천시",
  [Districts.GoyangSi]: "고양시",
  [Districts.YonginSi]: "용인시",

  // 강원도
  [Districts.ChuncheonSi]: "춘천시",
  [Districts.WonjuSi]: "원주시",
  [Districts.GangneungSi]: "강릉시",
  [Districts.DonghaeSi]: "동해시",
  [Districts.TaebaekSi]: "태백시",
  [Districts.SokchoSi]: "속초시",
  [Districts.SamcheokSi]: "삼척시",
  [Districts.HongcheonGun]: "홍천군",
  [Districts.HoengseongGun]: "횡성군",
  [Districts.YeongwolGun]: "영월군",
  [Districts.PyeongchangGun]: "평창군",
  [Districts.JeongseonGun]: "정선군",
  [Districts.CheorwonGun]: "철원군",
  [Districts.HwacheonGun]: "화천군",
  [Districts.YangguGun]: "양구군",
  [Districts.InjeGun]: "인제군",
  [Districts.GoseongGunGangwon]: "고성군",
  [Districts.YangyangGun]: "양양군",

  // 충청북도
  [Districts.CheongjuSi]: "청주시",
  [Districts.ChungjuSi]: "충주시",
  [Districts.JecheonSi]: "제천시",
  [Districts.BoeunGun]: "보은군",
  [Districts.OkcheonGun]: "옥천군",
  [Districts.YeongdongGun]: "영동군",
  [Districts.JeungpyeongGun]: "증평군",
  [Districts.JincheonGun]: "진천군",
  [Districts.GoesanGun]: "괴산군",
  [Districts.EumseongGun]: "음성군",
  [Districts.DanyangGun]: "단양군",

  // 충청남도
  [Districts.CheonanSi]: "천안시",
  [Districts.GongjuSi]: "공주시",
  [Districts.BoryeongSi]: "보령시",
  [Districts.AsanSi]: "아산시",
  [Districts.SeosanSi]: "서산시",
  [Districts.NonsanSi]: "논산시",
  [Districts.GyeryongSi]: "계룡시",
  [Districts.DangjinSi]: "당진시",
  [Districts.GeumsanGun]: "금산군",
  [Districts.BuyeoGun]: "부여군",
  [Districts.SeocheonGun]: "서천군",
  [Districts.CheongyangGun]: "청양군",
  [Districts.HongseongGun]: "홍성군",
  [Districts.YesanGun]: "예산군",
  [Districts.TaeanGun]: "태안군",

  // 전라북도
  [Districts.JeonjuSi]: "전주시",
  [Districts.GunsanSi]: "군산시",
  [Districts.IksanSi]: "익산시",
  [Districts.JeongeupSi]: "정읍시",
  [Districts.NamwonSi]: "남원시",
  [Districts.GimjeSi]: "김제시",
  [Districts.WanjuGun]: "완주군",
  [Districts.JinanGun]: "진안군",
  [Districts.MujuGun]: "무주군",
  [Districts.JangsuGun]: "장수군",
  [Districts.ImsilGun]: "임실군",
  [Districts.SunchangGun]: "순창군",
  [Districts.GochangGun]: "고창군",
  [Districts.BuanGun]: "부안군",

  // 전라남도
  [Districts.MokpoSi]: "목포시",
  [Districts.YeosuSi]: "여수시",
  [Districts.SuncheonSi]: "순천시",
  [Districts.NajuSi]: "나주시",
  [Districts.GwangyangSi]: "광양시",
  [Districts.DamyangGun]: "담양군",
  [Districts.GokseongGun]: "곡성군",
  [Districts.GuryeGun]: "구례군",
  [Districts.GoheungGun]: "고흥군",
  [Districts.BoseongGun]: "보성군",
  [Districts.HwasunGun]: "화순군",
  [Districts.JangheungGun]: "장흥군",
  [Districts.GangjinGun]: "강진군",
  [Districts.HaenamGun]: "해남군",
  [Districts.YeongamGun]: "영암군",
  [Districts.MuanGun]: "무안군",
  [Districts.HampyeongGun]: "함평군",
  [Districts.YeonggwangGun]: "영광군",
  [Districts.JangseongGun]: "장성군",
  [Districts.WandoGun]: "완도군",
  [Districts.JindoGun]: "진도군",
  [Districts.SinanGun]: "신안군",

  // 경상북도
  [Districts.PohangSi]: "포항시",
  [Districts.GyeongjuSi]: "경주시",
  [Districts.GimcheonSi]: "김천시",
  [Districts.AndongSi]: "안동시",
  [Districts.GumiSi]: "구미시",
  [Districts.YeongjuSi]: "영주시",
  [Districts.YeongcheonSi]: "영천시",
  [Districts.SangjuSi]: "상주시",
  [Districts.MungyeongSi]: "문경시",
  [Districts.GyeongsanSi]: "경산시",
  [Districts.GunwiGun]: "군위군",
  [Districts.UiseongGun]: "의성군",
  [Districts.CheongsongGun]: "청송군",
  [Districts.YeongyangGun]: "영양군",
  [Districts.YeongdeokGun]: "영덕군",
  [Districts.CheongdoGun]: "청도군",
  [Districts.GoryeongGun]: "고령군",
  [Districts.SeongjuGun]: "성주군",
  [Districts.ChilgokGun]: "칠곡군",
  [Districts.YecheonGun]: "예천군",
  [Districts.BonghwaGun]: "봉화군",
  [Districts.UljinGun]: "울진군",
  [Districts.UlleungGun]: "울릉군",

  // 경상남도
  [Districts.ChangwonSi]: "창원시",
  [Districts.JinjuSi]: "진주시",
  [Districts.TongyeongSi]: "통영시",
  [Districts.SacheonSi]: "사천시",
  [Districts.GimhaeSi]: "김해시",
  [Districts.MiryangSi]: "밀양시",
  [Districts.GeojeSi]: "거제시",
  [Districts.YangsanSi]: "양산시",
  [Districts.UiryeongGun]: "의령군",
  [Districts.HamanGun]: "함안군",
  [Districts.ChangnyeongGun]: "창녕군",
  [Districts.GoseongGunGyeongsangnam]: "고성군",
  [Districts.NamhaeGun]: "남해군",
  [Districts.HadongGun]: "하동군",
  [Districts.SancheongGun]: "산청군",
  [Districts.HamyangGun]: "함양군",
  [Districts.GeochangGun]: "거창군",
  [Districts.HapcheonGun]: "합천군",

  // 제주특별자치도
  [Districts.JejuSi]: "제주시",
  [Districts.Seogwipo]: "서귀포시",
};

export function getDistrictDescription(code: string): string {
  if (code in Districts) {
    return districtDescriptions[parseInt(code) as Districts];
  } else {
    return "등록되지 않은 지역";
  }
}
